/**
*
* codes.js
*
* Success and error codes.
*
**/

// Success:
const SUCCESS_ARTICLE_FOUND_IN_INDEX = 1001;
const SUCCESS_COURSE_CREATED = 1002;
const SUCCESS_SAVING_COURSE_CREATION = 1003;

// Error:
const ERROR_ARTICLE_NOT_FOUND_IN_INDEX = 2001;
const ERROR_COURSE_NOT_CREATED = 2002;
const ERROR_NULL_STARTING_ARTICLE = 2003;
const ERROR_RETRIEVING_STARTING_ARTICLE_INDEX = 2004;
const ERROR_RETRIEVING_STARTING_ARTICLE_DATA = 2005;
const ERROR_NULL_ARTICLE_INDEX_LIST = 2006;
const ERROR_NULL_COURSE_RESULTS = 2007;
const ERROR_NULL_CREATING_TABLE_SAVING_COURSE = 2008;
const ERROR_NULL_INSERTING_INTO_TABLE_SAVING_COURSE = 2009;

module.exports = {
  SUCCESS_ARTICLE_FOUND_IN_INDEX,
  SUCCESS_COURSE_CREATED,
  SUCCESS_SAVING_COURSE_CREATION,
  ERROR_ARTICLE_NOT_FOUND_IN_INDEX,
  ERROR_COURSE_NOT_CREATED,
  ERROR_NULL_STARTING_ARTICLE,
  ERROR_RETRIEVING_STARTING_ARTICLE_INDEX,
  ERROR_RETRIEVING_STARTING_ARTICLE_DATA,
  ERROR_NULL_ARTICLE_INDEX_LIST,
  ERROR_NULL_COURSE_RESULTS,
  ERROR_NULL_CREATING_TABLE_SAVING_COURSE,
  ERROR_NULL_INSERTING_INTO_TABLE_SAVING_COURSE
};
