// const SUCCESS_ARTICLE_FOUND = 1001;
// const SUCCESS_COURSE_ARTICLES_FOUND = 1002;
// const ERROR_CONNECTING_TO_DB = 2001;
// const ERROR_NO_ARTICLE_FOUND = 2002;
//
// module.exports = {
//   SUCCESS_ARTICLE_FOUND,
//   SUCCESS_COURSE_ARTICLES_FOUND,
//   ERROR_CONNECTING_TO_DB,
//   ERROR_NO_ARTICLE_FOUND
// }
